name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Build (${{ matrix.target }})
        run: |
          echo "Building for ${{ matrix.target }}..."
          exit 1
